# Array Operations

In [3]:
import numpy as np
# Create an array
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
# Add 5 with each element
print(arr+5)

[ 6  7  8  9 10]


In [5]:
# Add two array
arr2=np.array([5,4,3,2,1])
print(arr+arr2)

[6 6 6 6 6]


In [10]:
# Arithmatic operations
print(np.sin(arr))
print(np.cos(arr))
print(np.max(arr))
print(np.min(arr))
print(np.sqrt(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
5
1
[1.         1.41421356 1.73205081 2.         2.23606798]


## Copying two Array

In normal copying the address of both arrays are same and item change in one array affect another array

In [16]:
# Normal copying
arr1=arr
print(arr1)
print(id(arr))
print(id(arr1))
arr1[1]=9
print('arr1 =',arr1)
print('arr =',arr)

[1 2 3 4 5]
1722153516688
1722153516688
arr1 = [1 9 3 4 5]
arr = [1 9 3 4 5]


In SHALLOW copying the address of both arrays are different
But
Item change in one array affect another array

In [20]:
# Shallow copy
arr1=arr.view()
print(arr1)
print(id(arr))
print(id(arr1))
arr1[1]=18
print('arr1 =',arr1)
print('arr =',arr)

[ 1 18  3  4  5]
1722153516688
1720305571360
arr1 = [ 1 18  3  4  5]
arr = [ 1 18  3  4  5]


In DEEP copying the address of both arrays are different
 But 
Item change in one array DOES NOT affect another array

In [21]:
# Deep copy
arr1=arr.copy()
print(arr1)
print(id(arr))
print(id(arr1))
arr1[1]=27
print('arr1 =',arr1)
print('arr =',arr)

[ 1 18  3  4  5]
1722153516688
1720320756432
arr1 = [ 1 27  3  4  5]
arr = [ 1 18  3  4  5]
