# Matrix In NumPy

### Create MAtrix

In [8]:
import numpy as nm
mat=nm.matrix('1 2 3 4 ; 2 0 0 3 ; 3 0 0 2 ; 4 3 2 1')# ;  s d f g h ; j k l z x")
print(mat)

[[1 2 3 4]
 [2 0 0 3]
 [3 0 0 2]
 [4 3 2 1]]


### Create matrix from File

In [23]:
mat_from_file=nm.genfromtxt('D:/Python/matrix.txt',int,delimiter=',') # Newline in txt file create a new line in matrix
#mat_from_file=nm.genfromtxt('D:\\Python\\matrix.txt',int,delimiter=',') # Nalternative of above code
print(mat_from_file,'\n')

[[ 11  22  33 111 222 333 444]
 [ 44  55  66 101 202 303 404]
 [ 77  88  99 909 808 707 999]] 



In [29]:
print(mat_from_file>500)

[[False False False False False False False]
 [False False False False False False False]
 [False False False  True  True  True  True]]


In [30]:
print( mat_from_file[mat_from_file>500] )

[909 808 707 999]


In [31]:
mat_from_file[mat_from_file<100]

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [27]:
mat_from_file

array([[ 11,  22,  33, 111, 222, 333, 444],
       [ 44,  55,  66, 101, 202, 303, 404],
       [ 77,  88,  99, 909, 808, 707, 999]])