# Multidimentional Array

In [3]:
import numpy as nm
# Creating a 2D array--
arr=nm.array([
    [1,2,3,4],
    [5,6,7,8],
    [4,3,2,1],
    [8,7,6,5]
])
print(arr)

[[1 2 3 4]
 [5 6 7 8]
 [4 3 2 1]
 [8 7 6 5]]


In [4]:
print(arr.ndim)     # Gives the dimention of the array
print(arr.shape)  #prints tuple of (rows,cols)
print(arr.size)     # Gives the number of items of array
print(arr.itemsize)     # returns size of one item
print(arr.nbytes)       # Returns total byteSize of the array
print(arr.size*arr.itemsize)        # Returns total byteSize of the array


2
(4, 4)
16
4
64
64


## Array Transformation

In [5]:
arr1=arr.flatten()  # Makes a mult-dim array to Single-Dim array
print(arr1)
arr2=arr1.reshape(8,2)  #returns array of 8*2 from an exixting array---where 8=Row 2=Col
print(arr2)

[1 2 3 4 5 6 7 8 4 3 2 1 8 7 6 5]
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [4 3]
 [2 1]
 [8 7]
 [6 5]]


## Transform arrays into Matrices

In [6]:
print(arr) #its an array
print()
mat=nm.matrix(arr)   #convert array in a matrix
print(mat)

[[1 2 3 4]
 [5 6 7 8]
 [4 3 2 1]
 [8 7 6 5]]

[[1 2 3 4]
 [5 6 7 8]
 [4 3 2 1]
 [8 7 6 5]]


* Why convert in numpy.matrix()

In [7]:
arr1=nm.array([
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4]
])
print(arr1*arr) # Array multiplication 
print()
mat1=nm.matrix(arr1)
print(mat*mat1) # Matrix multiplicaton
# See the output differences

[[ 1  4  9 16]
 [ 5 12 21 32]
 [ 4  6  6  4]
 [ 8 14 18 20]]

[[ 10  20  30  40]
 [ 26  52  78 104]
 [ 10  20  30  40]
 [ 26  52  78 104]]


## Create Matrix

In [8]:
mat=nm.matrix('1 2 3 4 ; 5 6 7 8 ; 8 7 6 5 ; 4 3 2 1')
print(mat)

[[1 2 3 4]
 [5 6 7 8]
 [8 7 6 5]
 [4 3 2 1]]


## Get Specific Rows and cols

In [9]:
print(arr,'\n')
print(arr[2,:],'\n') # Prints all cols of 3rd(2+1) row
print(arr[:,2],'\n') # Prints all rows of 3rd(2+1) col
print(arr[1:3,1:3],'\n')    #format-- arr[row,col]---where row,col = exclusive :(to) exclusive
print(nm.ones((2,2),int),'\n')
arr[1:3,1:3]=nm.zeros((2,2),int)
print(arr)

[[1 2 3 4]
 [5 6 7 8]
 [4 3 2 1]
 [8 7 6 5]] 

[4 3 2 1] 

[3 7 2 6] 

[[6 7]
 [3 2]] 

[[1 1]
 [1 1]] 

[[1 2 3 4]
 [5 0 0 8]
 [4 0 0 1]
 [8 7 6 5]]


Pass  A List as Index

In [12]:
print(arr[[1,2]],'\n')
arr3=nm.array([11,22,33,44,55,66,77,88,99,0])
lists=[2,5,3,4,1]
print(arr3[lists])


[[5 0 0 8]
 [4 0 0 1]] 

[33 66 44 55 22]
