# NumPy in Python

In [1]:
import numpy as np

In [8]:
# List to array
list1=[1,2,3,4,5,6]
list_to_array=np.array(list1)
print(list_to_array)
print(list_to_array.dtype)
print(list_to_array.shape)

[1 2 3 4 5 6]
int32
(6,)


In [16]:
# Create array using array func
arr1=np.array([[1,2,3,4,],[4,3,2,1]])
print(arr1)
print(arr1.dtype)
print(arr1.shape)

[[1 2 3 4]
 [4 3 2 1]]
int32
(2, 4)


In [38]:
#--array with all zeros
zeroArr=np.zeros(shape=(4,4),dtype=int)
print(zeroArr,"\n")
#--array with all ones
oneArr=np.ones(shape=(4,4),dtype=int)
print(oneArr,"\n")
#--array with all one values
allArr=np.full(shape=(4,4),fill_value=5,dtype=int)
print(allArr,"\n")
#--array with random values(int)
randArr=np.random.randint(low=0,high=10,size=(4,4),dtype="int32")
print(randArr,"\n")
#-- arrayy with random_values(float)
randArr1=np.random.rand(4,4) # give values between 0 1
print(randArr1,"\n")
randArr2=np.random.randn(4,4) # give values between 0 1
print(randArr2,"\n")

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] 

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]] 

[[5 0 3 7]
 [8 7 9 3]
 [7 6 3 5]
 [2 1 7 8]] 

[[0.79964327 0.74712981 0.72511105 0.08520294]
 [0.12049998 0.15972699 0.27111986 0.5154805 ]
 [0.09503466 0.88017705 0.51724522 0.40410446]
 [0.81550248 0.95763338 0.62848667 0.24902443]] 

[[ 2.38090246  0.94573216  0.24747785  4.17584873]
 [ 0.16041716 -0.63196929 -1.18246002 -0.35734161]
 [ 0.95185086 -0.36678164 -0.12692433 -1.60363245]
 [-0.82732545  1.32015996 -0.96518303  0.16392307]] 

